### ISSUE TITLE
Make a view on the datastore that gives a giant table of grants based on the Latest data

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#17]

**Comment by Bjwebb** [comment]
Here's the view I've been using.

```sql
CREATE VIEW view_latest_grant AS
    SELECT db_grant.*
        FROM db_grant
        INNER JOIN db_sourcefile_latest ON db_grant.source_file_id=db_sourcefile_latest.sourcefile_id
        INNER JOIN db_latest ON db_sourcefile_latest.latest_id=db_latest.id
        WHERE db_latest.series='CURRENT';
```

@michaelwood might want to take a look, and check it makes sense.

**Comment by michaelwood** [comment]
That looks right to me. 

I am still thinking that adding a new fk to shortcut to Grant from Latest, so that you don't have to go via sourcefile in the db schema, it will slow down the Latest update process as it will have to iterate through all the grants in each sourcefile but it makes running checks and various other lookups a lot simpler and it appears to be quite a common need (and for example I could remove Latest.total_grants ).

**Comment by Bjwebb** [comment]
I don't have a strong opinion on further fks. I've only had to write this view once, and then I've been able to make use of it for everything else I've done.

Currently, this view definition lives in the database — should it be stored in this repo somewhere?

**Comment by michaelwood** [comment]
We ended up building this into the database schema as it was useful elsewhere, no view is actually required anymore.
