### ISSUE TITLE
Standardising location data as far as possible

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#29]
From @drkane : 

> for beneficiary location (and recipient locations without postcode), a procedure that standardises the data to as much of an extent as possible, by locating every area within a ward/lsoa/local authority depending on the scale. This is probably the most complex part, but a rules-based approach should be doable.

So, this is an exercise in "filling in the blanks". Obviously, we can't go *more* granular than the existing data supports, but we can ensure that we have all of containing geographies in the data. 

We could use an external service, but we don't have any existing code that does this. Something like MapIt might make sense, but that's a paid-for service. There might be free alternatives, but they might not support the volume of requests that we would make. 

We do already use some extra data - we do this by having the files on disk and then using those files in various scripts. That works for small files, but NPSL (for example) is >1GB uncompressed. We should be able to load it into a postgres table easily and interact with it there, though. 

I'm don't have a good grasp on the resources available to do this. @drkane, @KDuerden - apart from NPSL are there any geo lookup files/services that come to mind that we could use here?

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Datastore - standardising location data as far as possible](https://trello.com/c/DIcrDI3x/60-datastore-standardising-location-data-as-far-as-possible)

**Comment by drkane** [comment]
The ONS geoportal is a good place to start in terms of lookups from one geography to another. It quickly gets messy though. They do have some lookups from incompatible areas based on the best fit between them - eg LSOA to wards. You can also reverse engineer something from the full NSPL table.

I have the findthatpostcode.uk website which does something similar to mapit, but it's definitely not set up for high-volume usage. MapIt can also do lookups based on boundaries which findthatpostcode doesn't do (child -> parent relationships are only shown where they are in the lookups).

One thing that would definitely be useful here is a list of what code types have been included as beneficiary data - this will help us work out where best to target. I think something that handles ward, LSOA, local authority and postcodes would get us quite far.

**Comment by robredpath** [comment]
Main value we can do here is getting a framework in place that we can expand on. This is predominantly about beneficiary location. A good useful first step would be getting as many grants as possible into LAs. @drkane will start this with some data investigation.

**Comment by drkane** [comment]
Results of data investigation:

 - 109,955 grants include some sort of beneficiary details, that's about 30%. 
 - Most of these recipients (93,000) only include one beneficiary location.
 - Sport England is the publisher that accounts for most of the grants with more than 1 location. They have 15,900 grants each with 4 location given. These locations are a postcode, LSOA, local authority and parliamentary constituency - but all relate to the same area. The LSOA could be used in this case.

## What values are used

Excluding Sport England, the following types of data are used:

Code type | count | percent of grants
---|----:|----:
Other  | 43613 | 40%
GSS code             | 35451 | 32%
Postcode outcode   | 16499 | 15%

The ideal data is to have a GSS code. This can be matched to an area based on the ONS data.

The postcode outcodes (the first part of the postcode, eg `SE1`) are from the Co-operative Group.

## "Other" values

Around 38,000 of the "Other" values have a value in the `location.name` field instead of the `location.geoCode`. There are 1,800 unique values used, of which the first 16 values make up about half between them:

Value in `name` column  | beneficiaryLocation.name | proportion of values
-- | --:| --:
UK | 3804 | 10%
South East | 1957 | 5%
Northumberland | 1656 | 4%
London | 1521 | 4%
North East | 1464 | 4%
Tyne & Wear | 1348 | 4%
North West | 1295 | 3%
South West | 1244 | 3%
Scotland | 933 | 2%
Newcastle Upon Tyne | 918 | 2%
UK Whole | 910 | 2%
West Midlands | 796 | 2%
Trafford | 738 | 2%
East Midlands | 687 | 2%
National | 677 | 2%
Eastern | 634 | 2%

These values look like they could be matched to countries, regions or local authorities.

## GSS Codes used

The following table shows the GSS codes used (by prefix) and the useful level of detail you can get from them:


GSS Code Prefix | Code type | Number of grants | Minimum viable area
-- | -- | --:| --
E01 | Lower Super Output Areas (LSOA) | 11206 | Ward
E07 | Non-metropolitan Districts | 4543 | Local Authority
E09 | London Boroughs | 4296 | Local Authority
E06 | Unitary Authorities | 3437 | Local Authority
E92 | Country | 2939 | Country
E08 | Metropolitan Districts | 2933 | Local Authority
K02 | United Kingdom | 1329 | Country
S12 | Council Areas | 1300 | Local Authority
E12 | Regions | 953 | Region
E05 | Electoral Wards/Divisions | 885 | Ward
W06 | Unitary Authorities | 722 | Local Authority
N09 | Local Government Districts | 403 | Local Authority
W01 | Lower Super Output Areas (LSOA) | 257 | Ward
S92 | Country | 92 | Country
N92 | Country | 55 | Country
W92 | Country | 44 | Country
E14 | Westminster Parliamentary Constituencies | 18 | Local Authority
K04 | England and Wales | 14 | Country
K03 | Great Britain | 11 | Country
S01 | Data Zones | 10 | Ward
S13 | Electoral Wards | 3 | Ward
E11 | Metropolitan Counties | 1 | Local Authority

## Summary

- 8% of grants can be matched to a ward
- a further 10% of grants can be matched to a local authority (from GSS code or postcode outcode)
- a further 10% of grants can be matched to a region or country (from GSS code or location name)
- 72% of grants can't be matched to anything

**Comment by drkane** [comment]
Based on the research above, I think what we should do is apply some standardisation to anything where they've used a GSS Code (in the format `[EWSN]010000001`) in the `GeoCode` field for the Location, and ignore anything else in the beneficiary location fields.

To do this we'll only need two lookup tables:

- LSOA (eg `E01000001`) to [Ward](https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=all(LUP_LSOA_WD))/[Local Authority](https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=all(LUP_LSOA_UTLA))
- [Ward to Local Authority to Region](https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=all(LUP_WD_LAD_CTY_RGN_GOR_CTRY))

Main outstanding issue would be whether LSOA > Ward look up (which is based on "Best Fit", and can give more than one possible ward for each LSOA) is good enough for our purposes.
