### ISSUE TITLE
Unexpected data in database

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#49]
I was recently running some queries on the database to understand the prevalence of certain characters in grant IDs in the 360Giving corpus. 

I was doing this by running `SELECT * FROM db_grant WHERE grant_id like '%/%' LIMIT 10` . Yes, I know this will give me lots of duplicates, but for my purposes, that didn't really matter. 

The results included:
grant_id | data
---------|-----
"Generated By: Triangle Trust 28/05/2020 10:56"|"{"id": "Generated By: Triangle Trust 28/05/2020 10:56"}"

Similarly, with `SELECT * FROM db_grant WHERE grant_id like '%,%' LIMIT 10` : 
grant_id | data
---------|-----
"Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved."|"{"id": "Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved."}"

**Comment by robredpath** [comment]
This doesn't seem to affect the live data on GN - the Triangle Trust grants are showing up fine - but it might skew analysis of the corpus

**Comment by michaelwood** [comment]
I guess they had that in the bottom row col 1 of their spreadsheet for a while and have since removed it, it wouldn't have entered grantnav but would give an off by one on the number of grants from them. 

id | publisher (datagetter run)
------------ | -------------
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-05 01:22:37.035898+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-07 01:23:01.176284+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-06 01:23:04.635045+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-05-31 01:21:30.219189+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-01 01:21:13.195611+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-09 01:22:30.211364+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-08 01:22:44.269139+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-10 01:22:13.911194+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-02 01:21:40.166872+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-03 01:21:31.244880+00:00)
Generated By: Triangle Trust 28/05/2020 10:56|The Triangle Trust 1949 Fund (datagetter 2020-06-04 01:22:38.999029+00:00)

Same with the Copyright one

id | publisher (datagetter run)
---------------|-----------------
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-05 01:22:37.035898+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-07 01:23:01.176284+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-05-31 01:21:30.219189+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-06 01:23:04.635045+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-01 01:21:13.195611+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-08 01:22:44.269139+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-10 01:22:13.911194+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-09 01:22:30.211364+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-02 01:21:40.166872+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-03 01:21:31.244880+00:00)
Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved.|The Triangle Trust 1949 Fund (datagetter 2020-06-04 01:22:38.999029+00:00)

**Comment by michaelwood** [comment]
Just thought about this again this morning, you probably also want to make sure `data_valid` is true in your SQL. 

` SELECT db_grant.grant_id, db_sourcefile.data_valid from db_grant INNER JOIN db_sourcefile ON db_grant.source_file_id=db_sourcefile.id WHERE db_grant.grant_id LIKE '%,%' LIMIT 10 ;`

grant_id  | data_valid 
------------ | -------------
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
 Copyright (c) 2000-2020 salesforce.com, inc. All rights reserved. | f
(10 rows)
