### ISSUE TITLE
How do we reload data with minimal downtime / without showing misleading results?

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#5]

**Comment by michaelwood** [comment]
Some thoughts I had one this after having done a manual process this month:

Utilise the two servers by having them as a manual fail over system so that,

Green = Always latest, index goes from latest_next to latest and latest_previous on each load process they are renamed automatically every morning which causes them to switch datasets seamlessly.

Blue = Becomes a backup server, Slower but also automatic updates, always has an old known state / dataset/index available. Either a notification is generated “Blue will update itself to match current green in 2 days time" then that process could be halted if there was an issue. Or we could have a flag that is set on the datastore polling api to say "yes this dataset can go on green" and we use the datastore as a sort of orchestrator.

**Comment by michaelwood** [comment]
Note to self configurable grantnav index : https://github.com/ThreeSixtyGiving/grantnav/commit/a2ff3ec01c18c1ad751265e5fe482ce9188d0d26

**Comment by michaelwood** [comment]
The system uses a new ElasticSearch index each day, once it has been loaded it switches over to the new one and deletes the old one. This means there is no point at which the server is showing as loading. https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/grantnav/reload_latest_daily.sh
