### ISSUE TITLE
Funders that have changed names appear using the old one? Or a random one?

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#7]

**Comment by drkane** [comment]
Current expected behaviour in GrantNav is apparently that the funder name is based on the first grant in the first file on the registry, based on the expectation that the registry is ordered with the latest files first.

It would make sense to me if we picked up the funder name from the latest grant (based on `awardDate`) for each funder ID.

I think this query would do this, not sure how it would translate to django:

```sql
select
	distinct on (g."fundingOrganization.0.id") "fundingOrganization.0.id",
	"fundingOrganization.0.name"
from (
select 	to_date(data->>'awardDate', 'YYYY-MM-DD') as "awardDate",
	data->'fundingOrganization'->0->>'id' as "fundingOrganization.0.id",
	data->'fundingOrganization'->0->>'name' as "fundingOrganization.0.name"
from db_grant
	inner join db_getterrun
		on db_grant.getter_run_id = db_getterrun.id,
	(select max(datetime) as datetime from db_getterrun) as latest_run
where db_getterrun.datetime = latest_run.datetime
order by "awardDate" desc
) as g;
```

NB I guess the same would apply to Recipient Organisations, except that we would have less confidence that the latest name would be the correct one.

**Comment by KDuerden** [comment]
National Lottery Community Fund name change is now present in their grants data. The first file in the registry using the new National Lottery Community Fund name but dev GN is using Big Lottery Fund still for the filter and funder view.

**Comment by michaelwood** [comment]
Linking grantnav issue - https://github.com/ThreeSixtyGiving/grantnav/issues/519

**Comment by michaelwood** [comment]
We now use the same mechanism as grantnav for determining the right name for a org that has changed its name. Once we switch to using the datastore as the only source of data we can just have this mechanism in one place rather than grantnav and datastore.
