### ISSUE TITLE
Expand `status.json` and `coverage.json` outputs from datastore

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/datastore#8]

**Comment by michaelwood** [comment]
There turned out to be an issue with configuration of grantnav where we were pointing to the old file path in the datagetter package for what is effectively `status.json`. I think the table that showed this as broken is now fixed (see http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/datasets/ ) In terms of running other tests on the data I suggest that we have a look at what is actually needed and whether this is done separately or indeed covered by the daily testing on the travis instance.

**Comment by drkane** [comment]
So our thinking here was relating to being able to use the power of the datastore to improve what's in status.json and coverage.json, particularly in relation to how we monitor publishers & the data that's available for users.

As an example, it's great to know the number of unique recipients, but as source.json is based on file-level data it's not possible to aggregate this to a publisher level. You can easily sum the number of grants, but you can't sum the unique recipient counts. So if it's possible to reporoduce status.json but at a publisher level that would be very useful.

Something else we've talked about is the ability to access Funder-level rather than Publisher-level or File-level data. Particularly where there are multiple funders per file it would be useful to see how they differ in quality (particularly relating to the eventually forthcoming government data).

**Comment by robredpath** [comment]
If we switch to using the datastore for this, we should be mindful that the Registry uses this data to ascertain some stuff. We might want to have a "last available at" or "last validated at" kind of logic. See https://opendataservices.plan.io/issues/21925 (ODSC/360 internal link)

**Comment by michaelwood** [comment]
Whilst doing a request for a full coverage.json I tied it into this work as creating some new scripts to run on data also helps with this. 

I have now implemented a cron job on the datastore with the new scripts branch of the datatester https://github.com/ThreeSixtyGiving/datatester/pull/49  In doing this I also found the bug that was stopping the travis instance from running so pending merging the pull request it should start working again: 
https://travis-ci.org/ThreeSixtyGiving/datatester/builds/587012737

**Comment by michaelwood** [comment]
We did this
